### ISSUE TITLE
Initial Loading Error

### ISSUE THREAD

**Issue by hoofta** [geaz/simplyRetro-Z5#1]
I used Etcher to load on the .img file and after showing the initial "SimplyRetro" logo I ended up getting this error (image attached)
![IMG_20190605_154519](https://user-images.githubusercontent.com/33319399/58985514-7a255300-87a9-11e9-8e68-2daa48384722.jpg)

**Comment by geaz** [comment]
Which Pi are you using? Because the image is build for the Pi Zero W. Just asking to make this clear :)

**Comment by hoofta** [comment]
Pi Zero W V1.1

**Comment by geaz** [comment]
You could get the error because of several things. I built the image especially for the Z5. Therefore it could come to errors, if the power button is not present for example.

We could try two things:
1. Remove this line "dtoverlay=gpio-poweroff,gpiopin=7,active_low=1" from the config.txt
2. Because of a script, which gets started at the boot of the image, the GPIO 19 has to be pulled to LOW. Otherwise a shutdown will be initiated before it really booted...(this looks like the error you are getting)

**Comment by geaz** [comment]
You could get the error because of several things. I built the image especially for the Z5. Therefore it could come to errors, if the power button is not present for example.

We could try two things:
1. Remove this line "dtoverlay=gpio-poweroff,gpiopin=7,active_low=1" from the config.txt
2. Because of a script, which gets started at the boot of the image, the GPIO 19 has to be pulled to LOW. Otherwise a shutdown will be initiated before it really booted...(this looks like the error you are getting)

**Comment by hoofta** [comment]
Line removed commented out. Booted up, SimplyRetro logo came up and then pi shut down ("no signal appeared on screen"). I ordered the parts so I guess I might need to wait for them to arrive.

**Comment by geaz** [comment]
Yep, seems like it is the shutdown script. Will try to add a config for this one in the following days (after I finished the "Build" chapter).

**Comment by hoofta** [comment]
Very cool. I'll stay in contact when I get parts for build and keep you posted to help with more troubleshooting if I can. Thanks for your efforts on this. Definitely looks like a fun project. Can't wait!

**Comment by geaz** [comment]
I will try my best to help you :)
Please be aware, that I added a Veroboard / Stripboard to the BOM. This is necessary for the safe shutdown and battery monitoring.

**Comment by hoofta** [comment]
Do you have a link for the veroboard you used?

**Comment by geaz** [comment]
Any Veroboard like this one will do it: https://www.amazon.com/ST3U-StripBoard-3U-Uncut-Strips-Sided/dp/B00C9NXP94/ref=sr_1_1?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=stripboard&qid=1559770029&s=gateway&sr=8-1

It does not have to be that big. You will just need a 1x4, a 8x10 and a 8x9 piece.
Here are the pictures of the circuits for which it is needed:
https://github.com/geaz/simplyRetro-Z5/blob/master/images/c1.png
https://github.com/geaz/simplyRetro-Z5/blob/master/images/c2.png

**Comment by geaz** [comment]
Added retropower.cfg to boot partition and changed power script to read this file on start. If you used another pin than GPIO 19 (WiringPi 24) just change it in this file. Or remove the file to disable the power script.

New image added to release V1.1
